### ISSUE TITLE
Idea: roll initiative and reorder creatures based on initiative

### ISSUE THREAD

**Issue by Povilas-Marcinkevicius** [Kramst/turn-tracker#10]
Have two buttons: one auto-rolls initiative (with appropriate modifiers as entered) for all creatures and another button to rearrange creatures in the initiative order. This would allow for players to hand-roll initiative and for you to replace its' value in the system before character arrangement. Letting players roll feels right, but up to you, could 100% automate it.

Currently Initiative doesn't seem to do anything.

**Comment by PineappleOverTheSea** [comment]
Added for creatures. Players will be implemented in the future.
