### ISSUE TITLE
Idea: Adding N creatures with incrementing names

### ISSUE THREAD

**Issue by Povilas-Marcinkevicius** [Kramst/turn-tracker#11]
When adding a creature, could check for duplicates in the name. If there's a duplicate, check if the name end in a number. If not, append " 1" to the end of the originals name. Then increment the number of the highest duplicate. This would allow to match specific creatures with ones on the table since they have unique IDs.

Example: you want to add 5x guard, so you enter the stats (let's say name is "Guard") and click "Add Creature" 5 times. First one to come out is "Guard". Upon second entry, the first one becomes "Guard 1", the new one "Guard 2", etc.

**Comment by PineappleOverTheSea** [comment]
added
