### ISSUE TITLE
Heal and Hurt issues

### ISSUE THREAD

**Issue by Povilas-Marcinkevicius** [Kramst/turn-tracker#9]
These values reset total hp to <blank> if they are blank. This will 100% make someone accidentally lose the current HP. Make those field always have a number, or perhaps add a check upon pressing enter.

Also, if your cursor is on Heal but you edit the Hurt number using the up/down arrows, pressing enter activates Heal. Feels like the up/down arrows shouldn't be there, and that intended use is to enter a number by hand, so might wanna get rid of them arrows...

**Comment by PineappleOverTheSea** [comment]
Works on chromium
